---
- name: Yaml Playbook to fetch the App module version deployed on each server
  hosts: DIT
  gather_facts: True
  ignore_errors: False
  roles:
    - role : node_fetch
      AppPath: /ciohosting/cce2e/{{ EnvName }}/cce2e-383-mule/apps/
      EnvName: dit1
      when: ansible_default_ipv4.address    == '10.0.2.15'

    - role : node_fetch
      AppPath: /ciohosting/cce2e/{{ EnvName }}/cce2e-383-mule/apps/
      EnvName: dit2
      when: ansible_default_ipv4.address    == '10.0.2.15'
  tasks:
   - name: execute report_final.sh script to generate final .csv file.
     shell: ./report_final.sh "{{ dest_node }}" "{{ src_node }}"
     delegate_to: 127.0.0.1
     register: Final_CSV


...

