---
- name: Yaml Playbook to fetch the App module version deployed on each server
  hosts: DIT                                                       # this is the server group for which we want to execute this playbook
  gather_facts: True                                               # we want to gater facts about the remote systems so we can use them
  ignore_errors: False                                             # Generally playbooks will stop executing any more steps on a host that has a task fail. Sometimes, though, you want to continue on. To do so, we use this
######## adding new logic from here 1.1  
  tasks:
   - name: Execute Shell command to remove old files 
     shell: rm -rf  report_*.csv Report_finalR.csv  status*txt
     delegate_to: 127.0.0.1                                           # this step make sure we execute this task on local system.
######## ending new logic here 1.1  

			
  roles:
    - role : node_fetch                                               # Invoking node_fetch role to be executed with below variables only if when condition is true
      AppPath: /ciohosting/cce2e/{{ EnvName }}/cce2e-383-mule/apps/   # Setting the application variable here only if when condition is true
      EnvName: dit1                                                   # Setting the environment name variable here only if when condition is true
      when: ansible_default_ipv4.address    == '10.0.2.15'            # This when condition will trigger the node_fetch role only when ip address matches. 

    - role : node_fetch                                               # Invoking node_fetch role to be executed with below variables only if when condition is true
      AppPath: /ciohosting/cce2e/{{ EnvName }}/cce2e-383-mule/apps/   # Setting the application variable here only if when condition is true
      EnvName: dit2                                                   # Setting the environment name variable here only if when condition is true
      when: ansible_default_ipv4.address    == '10.0.2.15'            # This when condition will trigger the node_fetch role only when ip address matches. 
  tasks:
   - name: execute report_final.sh script to generate final .csv file.
     shell: ./report_final.sh "{{ dest_node }}" "{{ src_node }}"      # this shell module will trigger report_final.sh and this will analyze the report_env?.csv files and create a file report_final.csv with all environmnet and their modules version. and also it wil create a file with all the version that are present on source and missing on dest node.  
     delegate_to: 127.0.0.1                                           # this step make sure we execute this task on local system.
     register: Final_CSV                                              # we are stroging the data in this register


...
